### ISSUE TITLE
Lags the Cr@p out of minecraft

### ISSUE THREAD

**Issue by SockNinja** [Funwayguy/Epic-Siege-Mod#1]
The dev build of epic seige drops my minecraft framerate from my usual 30 fps to a weird slideshow, pushing the processor to max speed. Don't get me wrong, I love the mod, I'm just reporting bugs. The game will not shut down properly. I must use the task manager to kill the program. And the deobf version simply crashes. I couldn't get the report because the launcher just freezes up. In the meantime, I think I'll stick to 1.5.2.

Laptop specs
Asus X550
windows 8.1
intel pentuim cpu 2117U @ 1.80 GHz
8G Ram, 750G HDD

**Comment by Funwayguy** [comment]
After digging through the code I think I've finally found the problem and fixed it. Lag should be gone for the most part in the next update.

**Comment by Funwayguy** [comment]
Should be all fixed up now. Sorry for the REALLY long wait for this to be fixed but hey, better late than never. Plus most of the back end of the mod is more robust enough to deal with the processing load now than it it was before.
