### ISSUE TITLE
Crash with Charged Creeper Explosion

### ISSUE THREAD

**Issue by louisw22** [Funwayguy/Epic-Siege-Mod#11]
I am using Latest Epic Siege Mod (EpicSiegeMod-10.0.102)
Crash Report: http://pastebin.com/fxiNS0AG
The crash report seems to suggest that maybe a zombie crashes the game?

- Yes I'm back with more crash reports and testing for you, the tps lag fix is amazing

**Comment by Funwayguy** [comment]
Should be fixed in build 103.

**Comment by louisw22** [comment]
I thought so, thanks
