### ISSUE TITLE
Add an option for bossModifier to not affect speed

### ISSUE THREAD

**Issue by martmists** [Funwayguy/Epic-Siege-Mod#113]
We are using ESM in our pack with an insanely high modifier for boss kills, but this is causing some issues after killing just 4 bosses; The mob speed has gotten a 1.75^4=9.4 times multiplier, which makes it impossible to deal with. However, at this point we have no problems dealing this much damage. Please add an option to make this not affect speed.

**Comment by Funwayguy** [comment]
Added additional options in build 165 for this
