### ISSUE TITLE
ESM Causes cascading chunk loading

### ISSUE THREAD

**Issue by martmists** [Funwayguy/Epic-Siege-Mod#116]

**Comment by Funwayguy** [comment]
Going to need a lot more information on this one for me to even beginning pinning down exactly how cascading is occurring from entity AI.

**Comment by martmists** [comment]
It seems entity AI path generates new chunks to find their path, these new chunks spawn entities, which also load chunks for pathfinding.

**Comment by TowardtheStars** [comment]
So did I encountered the problem.
Here is what happened when I tried to start a whole new game only with this mod and Journey Map. I set hardness to difficult, view distance to 2(minimum), and Awareness Radius in config of this mod to 128(64 by default).

At first, everything appeared normal. And command `/forge entity list` told me that there are 20 entities in 9 chunks around me. Then I set time to 16000 and game rule doDaylightCycle to false to make hostile mobs begin to spawn. After 30 minutes of waiting or less, here is what I got.
<img width="257" alt="awareness_radius_128" src="https://user-images.githubusercontent.com/29396015/62834381-ec208980-bc7d-11e9-9788-07be3ecff6da.png">

And after another 5 minutes, there are 4182 entities loaded.

This is definitely abnormal.

**Comment by TowardtheStars** [comment]
I guess it is the enemy-searching process that causes the problem. When searching for targets to attack, mobs will load chunks that are around themselves but not inside players' view distance. And as said before, mobs will be spawned inside these extra chunks, and keep loading more chunks.

**Comment by Yourname942** [comment]
Is this still an issue, or is it fixed?

**Comment by da3dsoul** [comment]
The best way to fix this, as far as I can tell, is to add a chunkExists() check and return false on the pathing check preemptively to prevent the call to the chunk from generating it. This will likely fix many other performance issues, as well.

**Comment by Funwayguy** [comment]
Looked into this issue again and the issue isn't necessarily coming from ESM but vanilla Minecraft's path navigator. I'll probably have to hack in an override to fix their own bug.

PS: I know ESM has been somewhat neglected since I dedicated most of my time to Better Questing and Ore Excavation so I apologise but updates will still be slow and far between for the considerable future.

**Comment by Funwayguy** [comment]
Update was published yesterday which should fix this plus some other crazy BS vanilla was pulling (loaded every chunk around the player equivalent to search range even if they were right next to you)
