### ISSUE TITLE
Creative mob attacks

### ISSUE THREAD

**Issue by MyasisDragon** [Funwayguy/Epic-Siege-Mod#12]
using ESM 10.0.103, if you create a survival world with cheats on, enter a new world, gain aggro, then then turn your gamemode to "1", mobs will still try to attack, doing no damage. Creepers will explode causing no damage to you, but making a hole in the landscape as usual. It's as if they are not dropping their target once you are in creative mode in a survival world. If I disable ESM, then enter the same world (still in gamemode 1), the mobs just walk away as if they are oblivious to me. Turn ESM back on, and they ignore me (in gamemode 1) as you would expect. 

It only seems to happen if you enter the world in survival mode and then change your /gamemode 1 after gaining aggro from the mobs. if no mob ever aggro'd you and you enter /gamemode 1, they always ignore as normal.

**Comment by Funwayguy** [comment]
Just tested this in version 10.0.104 and it didn't happen. All aggressive mobs immediately stopped attacking the player after changing to creative mode. Are you sure you are using proper creative mode and not NEI's Creative+

Note; 103 has a crash with Zombies picking up pickaxes so I wouldn't recommend using it.
