### ISSUE TITLE
Server freeze, causes crash and world rollback.

### ISSUE THREAD

**Issue by TinTheBeast** [Funwayguy/Epic-Siege-Mod#13]
The server freezes, and basically crashes, traced it down to being caused by the Epic Siege Mod by process of elimination, removed all mods that affect mobs except Epic Siege, still had error.
Here's a pastebin of the log.  

Things that should be noted:
Forge Verison: 1370
Running Cauldron
The crash only happens around night-time, we believe after one of us dies to a ranged attack.

http://pastebin.com/trcNF4G9

**Comment by Funwayguy** [comment]
This appears to be an incompatibility with BattleGear2 and what they are doing with projectiles. I will try and fix it but BattleGear2 has been known to be incompatible with a LOT of other mods so I don't have high hopes

**Comment by Funwayguy** [comment]
I think I've fixed this for next release however I have a feeling the fix will cause some side effects with other projectile firing mobs.

**Comment by TinTheBeast** [comment]
If you can't fix it, just have your users disable the chance for custom arrow spawning on skeletons; that's how I just fixed it. Just set all chances to 0.0.
