### ISSUE TITLE
Swimming AI NPE Crash

### ISSUE THREAD

**Issue by Sailren** [Funwayguy/Epic-Siege-Mod#16]
used version is 10.0.109 and fastcraft is installed

well, no idea how i can describe this properly, it's something with swimming yeah

http://paste.ubuntu.com/11310962/

here a better report: http://openeye.openmods.info/crashes/0c8bb12a0ae6259e49da34deffa9d69c

**Comment by ivardensphere** [comment]
I can concur this does happen and quite often, bringing down the server. I can also post my crash log if needed but Sailren has the same thing I do in his basically. I did post this on Father Toast's MCF just to give out information as well to him.

**Comment by Sailren** [comment]
the funny thing, the mob is a custom one from toasts mod, since he disables almost all vanilla and replaces them with his own

**Comment by Funwayguy** [comment]
Fixed for next release
