### ISSUE TITLE
10.0.112 does not respect Allow Sleep=True

### ISSUE THREAD

**Issue by Mechalith** [Funwayguy/Epic-Siege-Mod#18]
No error message or anything, but right clicking on a bed does nothing.

Exact same config file worked fine in 10.0.106, I double checked. Deleting and re-creating the cfg, then updating the setting and relaunching has no effect either.

(I'm running the 0.0.6 version of DrasticDemise's Banished modpack, for reference.)

**Comment by Funwayguy** [comment]
Do you have 'Enforce Global Default' turned on? If so the world specific configs will be ignored and the settings set in the config directory will apply instead.

**Comment by Mechalith** [comment]
OK... so I checked, and you're right, I did have 'Enforce Global Default' turned on. I'd created a new world specifically for testing and I'd assumed (incorrectly, it seems) that a new world would be created with options that matched the ESM.cfg file and not the *default values* of the ESM.cfg file. Now that I've changed the Enforce Global setting, it is behaving as I expected it to.
