### ISSUE TITLE
Mobs having difficulty pathfinding through tallgrass

### ISSUE THREAD

**Issue by Xltimus** [Funwayguy/Epic-Siege-Mod#20]
Forge 10.13.4.1448
ESM 10.0.115
Config: (http://pastebin.com/mCJQ6Nd4)

Mobs attempt to reach its target and/or wander, but often get stuck in tallgrass (and likely maybe other non-opaque blocks). When stuck, they'll frantically jump around and spin in circles.

**Comment by Funwayguy** [comment]
Might be a side effect of a change I made to the pathing AI. I'll take a look at it soon to see what exactly caused it.
