### ISSUE TITLE
Blazes not spawning in Overworld in recent versions

### ISSUE THREAD

**Issue by Taliel81** [Funwayguy/Epic-Siege-Mod#21]
I can't get any blazes to spawn naturally in the Overworld. They did spawn in version 108, but after updating to 112 and then to the following versions they will no longer spawn.

My settings for them are:

Blaze {
    I:"Dimension Blacklist" <
     >
    I:Fireballs=9
    I:Rarity=9
    B:Spawn=true
}

**Comment by Insane-96** [comment]
This bug still affects 10.0.144

**Comment by Funwayguy** [comment]
Finally figured out why I didn't have this problem in testing. It seems if the global default was enforced then it would fail to apply the spawn settings. Ran a couple of tests after changing it and it should work just fine now in version 10.0.145

**Comment by Insane-96** [comment]
It's fixed, but ghasts spawn even in daytime, and at a really high rate (even with rarity: 100 it's spawned one every ~40 seconds)

**Comment by Funwayguy** [comment]
Ghasts spawning during the day isn't a bug, they've always ignored light levels. The spawn weight may be a little skewed since changing to scale to 1-1000 instead of 1-100
