### ISSUE TITLE
Server Crash with SpecialMobs

### ISSUE THREAD

**Issue by ivardensphere** [Funwayguy/Epic-Siege-Mod#22]
Hi there,

Found another crash dealing with special mobs.

https://gist.github.com/ivardensphere/12049c30ca912640bfa0

Seems to deal with specialmobs endermen and ESM.

ESM Version: EpicSiegeMod-10.0.111.jar
Forge Version: .1408

**Comment by ivardensphere** [comment]
Seems it's with any endermen from any mod.

https://gist.github.com/ivardensphere/cab473119bf797ea3197

Same crash but with endermen from Hardcore Ender Expansion.

**Comment by ivardensphere** [comment]
After doing some further digging, seems the slender mode causes the issues. 

Changing the server side configs to:

Enderman {
    S:Mode=Normal
    B:"Player Teleport"=false

    # Makes Endermen stalk players with side effects
    B:Slender-Mode=false

Solved the issue with the crashing endermen. Hope this helps track this one down and thanks!

**Comment by Funwayguy** [comment]
Looking into the issue more, it looks like a mod is modifying the potions that the Slenderman is using causing a crash when it attempts to use them. It's not necessarily the enderman's fault or its AI for the crash.

**Comment by Funwayguy** [comment]
Just added a crash handler to take care of this bug. Not sure what mod is responsible for the bug yet but for now the newest version of ESM should catch the error without crashing Minecraft.
