### ISSUE TITLE
Pathfinding in Water

### ISSUE THREAD

**Issue by Xltimus** [Funwayguy/Epic-Siege-Mod#24]
EpicSiegeMod10.0.122
Forge 10.13.4.1448

Mobs have difficulty attempting to find a path through water once submerged.

**Comment by Funwayguy** [comment]
There is quite some difficulty involved with path finding in water and Minecraft doesn't exactly support it either. I might think about working on it in future (as long as it doesn't kill TPS) but for now most of the time mobs aren't seriously affected by the lack of navigation underwater.

**Comment by CoolKidwho** [comment]
I'm experiencing bad problems with mobs in water they just spin around or stay there as soon as they enter the water please fix this problem.

**Comment by mrdeadlocked** [comment]
Have a similiar issue. Any little bit of water and they get stuck. https://db.tt/m95KS5cH

**Comment by Funwayguy** [comment]
Last few updates should have this fixed now.
