### ISSUE TITLE
Ticking entity error with Custom NPCs and this mod installed

### ISSUE THREAD

**Issue by Sunconure11** [Funwayguy/Epic-Siege-Mod#25]
http://pastebin.com/D7sUXaWD

**Comment by Funwayguy** [comment]
I actually have this fixed but I forgot to release the update for it when it was first reported. I'm not at my dev PC right now but I'll hopefully remember to push it out when I am. If it is up within 10-12hrs, feel free to bump this thread until I do.

**Comment by Sunconure11** [comment]
Bump since it's not up yet

**Comment by Funwayguy** [comment]
Update pushed out, sorry for the delay
