### ISSUE TITLE
Blacklist Toggle

### ISSUE THREAD

**Issue by mrdeadlocked** [Funwayguy/Epic-Siege-Mod#28]
Could we get a toggle to make the 'list' a blacklist instead of a whitelist. I'd liek to remove 3-4 mobs from ESM mob bombs, but instead it requires adding all the other mobs.

**Comment by mrdeadlocked** [comment]
Blacklist works great! Thanks!

**Comment by Funwayguy** [comment]
No problem. Let me know if you have any more troubles
