### ISSUE TITLE
10.0.137 Server crash

### ISSUE THREAD

**Issue by dirtyfargo** [Funwayguy/Epic-Siege-Mod#29]
Description: Server seems to crash every now and then due to a ticking Boat entity.
Version: 10.0.137
Forge version: 10.13.4.1558
Crash Report: https://gist.github.com/6d8d964095804df1b111

**Comment by Funwayguy** [comment]
Looks like I made a minor oversight in the server side boat AI. Fix coming in a couple of minutes.
