### ISSUE TITLE
John Cena was slained by Endermini

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [Funwayguy/Epic-Siege-Mod#31]
It seems that enderminis really don't get along with john cena creepers, I see this in my chat ( the phrase john cena was slained by endermini ) every few seconds during night time, could the john cena creeper have it's own rarity setting?
I like the new addition but the spawn rate it's a bit high I think.

Tank you for your time.

**Comment by Funwayguy** [comment]
Cena Creepers were just a fun Easter Egg and not really supposed to be used for proper gameplay so I didn't find it necessary to add a rarity option to them. I might add it in the next update though for those who do want a rare surprise.

I'm not really sure why the endermini would be attacking creepers though unless you had chaos mode on. They've always acted weird with the modified AI so it might be a better option to add them to the AI blacklisting

**Comment by Ganjalf-Amsterdoom** [comment]
Chaos mode on, check
Whitelisting of some mobs to let them use zombi awareness AI, check

I'd like the "rare" surprise, now it seems that each and every concussion creeper from enderzoo trigger a john cena.

]:D

**Comment by Funwayguy** [comment]
Well I just released an update to the mod which should give you the option to adjust Cena Creeper rarity. If you want mobs to stop killing eachother, turn off chaos mode.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you for your time \o/

**Comment by Ganjalf-Amsterdoom** [comment]
Funway, chaos mode was off, I just noticed now.

**Comment by Rahmiel** [comment]
Endermini's are coded to attack Creepers, its their thing in Ender Zoo. They literally only exist to attack creepers which sounds good in theory but in practice normally just causes random explosions. Anyways, that is why the enderminis are attacking your cena creepers.
