### ISSUE TITLE
Mobs spawning withing 8-12 blocks

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [Funwayguy/Epic-Siege-Mod#32]
Hello,

I set in esm to keep vanilla mechanics for spawning (i think) but mobs still spawn very close to me...between 8 and 12 blocks, did I miss something?

I just got my gravity skyblock blown up by a creeper that spawned about 9 blocks from me if not less :"D ( i have it on vod if you don't believe me )

Thank you for your time.

**Comment by Funwayguy** [comment]
The safe spawning radius is reduced on hardcore days and is completely intentional. Set hardcore days to 0 to disable this.
