### ISSUE TITLE
Advent of Ascension event specific mobs no longer event specific

### ISSUE THREAD

**Issue by Evstellar** [Funwayguy/Epic-Siege-Mod#34]
In Advent of Ascension, there are a number of time based events. During these events, special mobs will spawn in addition to the normal cadre of mobs. With ESM on board, these mobs become common occurrences, which is rather undesirable and ruins the wonder of the events. Plus, some mobs are ridiculously overpowered in groups when they should normally be rare solo mobs.

**Comment by Rahmiel** [comment]
Add them to the AI blacklist, easy.

**Comment by Funwayguy** [comment]
ESM does have hardcore days where more mobs spawn than usual but it never spawns something not on the spawn listing. Hardcore days can be set to -1 in the config to disable them and the AI blacklist will stop them from using the advanced behaviours.
