### ISSUE TITLE
Update feature request 

### ISSUE THREAD

**Issue by vadis365** [Funwayguy/Epic-Siege-Mod#37]
Hello Mate,
I was wondering if there was any chance you would be changing the fortress generation.
I'm not sure on your policies on contributions from other modders for things design wise, but if you are considering updating this feature at any point, I would be in interested in helping out.
Let me know. Cheers bud. I hope all is well for ya.
Cheers,
Me.

**Comment by Funwayguy** [comment]
Two unfortunate things about that: 1) Already started porting work for 1.9.4+ so I probably won't be making any changes to the 1.7.10 branch, 2) I've decided to discontinue structures and focus purely on the AI from now on.

**Comment by vadis365** [comment]
no worries mate - I just wanted a bash at making your fortress look a bit more fancy ;)

**Comment by vadis365** [comment]
Ah well, can't say I didn't offer to make that fugly thing a bit prettier :P

**Comment by Funwayguy** [comment]
Wow... shots fired much :/

**Comment by vadis365** [comment]
hehe :P
