### ISSUE TITLE
Modded Monsters Misbehaving

### ISSUE THREAD

**Issue by APolarBaer** [Funwayguy/Epic-Siege-Mod#46]
playing with ESM seems to make EvilCraft Vengence Spirits attack those who cant see them which they shouldnt, it also makes Wings, Horns, and Hooves, the Ultimate Unicorn Mods horses misbehave and hurt the player when they shouldnt be

**Comment by Hellcommander** [comment]
Yup enemies seem to keep hostile if attack a passive and they respawn

**Comment by Funwayguy** [comment]
Just add them to the AI blacklist. ESM can't know how every mob in every mod works or should work.
