### ISSUE TITLE
[1.10.2] lot of timeout

### ISSUE THREAD

**Issue by bloodyraoul** [Funwayguy/Epic-Siege-Mod#49]
Since the final version, i cannot anymore use the mod on my server
lot of lags and connection timeout ! unable to connect
Do you still have optimization to increase performance ?
thanks

**Comment by Funwayguy** [comment]
This is more up to how you configure the mod. I can only do so much to optimise it but if you leave it too high for your server infrastructure, it's not going to work well regardless.

**Comment by bloodyraoul** [comment]
The mod is doing stuff during chunk generation ?
I have let the default options...what can I decrease to have better performance ?

**Comment by Funwayguy** [comment]
Awareness radius, path capping and x-ray are 3 of the main areas you can usually get some performance improvements when configured correctly. I've also recently made a small update to fix some minor problems so that should help somewhat too if you haven't already updated.

**Comment by bloodyraoul** [comment]
Ok, i will try to reduce some params to 32 instead of 64
thank you
