### ISSUE TITLE
Extremely Low TPS With Build 10.0.87

### ISSUE THREAD

**Issue by louisw22** [Funwayguy/Epic-Siege-Mod#5]
Ever since I updated to ESM 10.0.087 Minecraft has had a very low TPS and has been crashing occasionally. 

Note: I do have Fastcraft Installed which Makes Optimizations to chunk loading, mob ai and many other things
Forge Version: Latest

Crash:
http://pastebin.com/AwV2DqbS

**Comment by Funwayguy** [comment]
It appears that crash is on FastCraft's side of things. The only involvement ESM has with that crash is a call to 'getPathEntityToEntity' and everthing after that is handled through vanilla methods until FastCraft gets involved with structure generation which results in an unhandled NULL crash.

As for the TPS lag, what are your current awareness radius settings and pathing cap? I usually recommend a radius of 48 and a cap of 8

**Comment by Adaptivity** [comment]
This crash related to vanilla Minecraft. Fixed by: https://github.com/MinecraftForge/MinecraftForge/commit/9704f25aa89415c2bb4ca4dd932a0ef8849ddf9e
