### ISSUE TITLE
Passive Mobs retaliate even when turned off in config

### ISSUE THREAD

**Issue by SamGunGraven** [Funwayguy/Epic-Siege-Mod#53]
Passive Mobs retaliate even when I have it turned off in config. This started happening after installing "Improving Minecraft" which adds wild versions of the animals that you have to domesticate. I would of course love it if you added compatibility with that mod so that the wild versions retaliated while the domesticated ones (after generations of breeding) didn't

**Comment by SamGunGraven** [comment]
Never mind, it's actually improving minecraft that adds the behavior without a config setting - SAFE TO CLOSE

**Comment by Funwayguy** [comment]
Sorry but I had to laugh a little at the 'improvement'. Hope you're issue gets resolved.
