### ISSUE TITLE
Mod conflict, causing server crashes with toroquest.

### ISSUE THREAD

**Issue by ProsperCraft** [Funwayguy/Epic-Siege-Mod#56]
Whenever a toro gets agro the server crashes, this does not happen when Epic Siege mod isn't in the pack.

https://github.com/ToroCraft/ToroQuest/issues/116#issuecomment-278377908

**Comment by GenDeathrow** [comment]
Should have posted this here... so both places. 

A fix for this is removing Toro from the ESM list. Thier is a config option in esm to remove certain entties as some may not like having AI replaced. Its normally up to pack devs to do this
