### ISSUE TITLE
Ticking Entity on new world

### ISSUE THREAD

**Issue by Drakma** [Funwayguy/Epic-Siege-Mod#61]
Getting a ticking entity error on world start up (new or old).  

https://pastebin.com/4pXnEZs1

ESM 11.0.152
1.10.2 with Forge 12.18.3.2254

Crashes with or without FoamFix

**Comment by Drakma** [comment]
Welp, that was easy.  Hardcore Farming does not play well with Epic Siege Mod.

**Comment by GenDeathrow** [comment]
Interesting.. wonder what the interaction issue is.
