### ISSUE TITLE
Server crash with console spam

### ISSUE THREAD

**Issue by frenzye** [Funwayguy/Epic-Siege-Mod#62]
Getting a strange crash where the server will start, start spamming this error, then eventually crash 

https://pastebin.com/raw/74WJXmEj

**Comment by GenDeathrow** [comment]
Just curious what mob mod do you have installed if any?

**Comment by frenzye** [comment]
There's gona be a number of them, originally this was occuring with some bigger names like Lycanites mobs, enderzoo, and deadlymonsters. since then I've removed all 3 of those, right now there's robot laser creepers , ars magica 2, toroquest, voidcraft, armorplus, infernal mobs, maybe a couple of others. issue persists

I thought the issue had something to do with the world save, but it persisted into a new world. I might be able to get some more detailed logs if that might help, this was given to me by someone else running my pack on their server after I forgot to tell them to turn off ESM

**Comment by Funwayguy** [comment]
Seems I forgot to put a check on how many Creepers can be stacked on one-another on spawn eventually hitting a point where it blows out the Java call stack

**Comment by Boolyman** [comment]
Im getting this same error... and I dont even have the option for creepers to spawn on heads enabled.  Worst thing is, this error didnt pop up until my modpack was 24hrs from release... really put a crink in my plans, I doubt there is any way this ticket is getting addressed any time soon.

**Comment by frenzye** [comment]
Yea this one came out of nowhere for me too, I really hope it does get addressed, I miss Funwayguy's AI!

**Comment by Funwayguy** [comment]
I actually fixed this on my side but got sidetracked and forgot to post the build up. Sorting that out now, should be downloadable shortly. Sorry about the wait

**Comment by frenzye** [comment]
I grabbed 154 and issue appears to persist with this error https://gist.github.com/frenzye/5334bbc114cd337037bdd747ac4b9c0f repeating endlessly in the console. Forge is at 2239

**Comment by Funwayguy** [comment]
_sigh_ I know why that last 'fix' did nothing. Seems I didn't account for order of operations. Let's try this again...

**Comment by frenzye** [comment]
This is definitely fixed on 11.0.156, working great
