### ISSUE TITLE
Crash On Server ESM 10.0.88

### ISSUE THREAD

**Issue by louisw22** [Funwayguy/Epic-Siege-Mod#7]
Crash:
http://pastebin.com/qndbihRd

**Comment by GenPage** [comment]
Can confirm, this happens on 10.0.90.

https://gist.github.com/GenPage/80f6aa5f14fe9d6881b9

**Comment by Funwayguy** [comment]
-__- I really got to stop doing late night coding and check these things. I'm pushing out a lag fix update soon so I'll include a fix for this when that comes out.

**Comment by Funwayguy** [comment]
Should be fixed in 91
