### ISSUE TITLE
Updated 1.10 branch to 1.12

### ISSUE THREAD

**Issue by LongHairedHacker** [Funwayguy/Epic-Siege-Mod#73]
Some of my friend are currently putting a mod pack together for 1.12.
They wanted to include this mod, so I decided to try and port the 1.11 branch to 1.12.
As it turns out the problems were mostly symbols that got renamed in the new version.
It compiles and it seems to work for us. (At least as well as the 1.11 branch.)

I'd send you a pull request, but I've never done minecraft modding before and it's bee few years since I've last used java.
So It is safe to assume I didn't really know what I was doing.

Anyway if you ever want to upgrade to 1.12 you might find my changes useful:
https://github.com/LongHairedHacker/Epic-Siege-Mod/tree/1.12

**Comment by Seth0067** [comment]
Thumbs up on this (whoever ends up releasing) Really want my napalm creepers for 1.12 pack!

**Comment by Dune-Jumper** [comment]
I wonder why it hasn't been officially updated yet.

**Comment by GenDeathrow** [comment]
Funwayguy's RL is currently more important. The only mod he is even working on is better questing. And his time is limited
