### ISSUE TITLE
Am I missing config options?

### ISSUE THREAD

**Issue by nepphhh** [Funwayguy/Epic-Siege-Mod#91]
My conf looks like this: https://pastebin.com/7FzRKYNz

I'm trying to set spawn frequency of Nether mobs but I see no options for that. I'd also like to set it so that x-ray vision only occurs on hard days, to reduce the mobs absolutely tearing up the underground endlessly. Seems like if you settle above a cave with all options on (x-ray, breaching, pillaging, digging), you'll get a huge torn-up mess of cobblestone and death. I've got gravity partially enable on cobble, so that's probably contributing.

**Comment by Funwayguy** [comment]
This was removed post 1.7.10 so that I could focus more on AI based features. There are other mods better suited to managing custom spawn tables and rarity weights nowadays anyway.
